### ISSUE TITLE
problema com a logica do valor total positivo e negativo

### ISSUE THREAD

**Issue by Toledodev** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-e1-proj-web-t2-daybyday#26]
Apos adicionar os valores ficam errados

<img width="788" alt="image" src="https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-e1-proj-web-t2-daybyday/assets/87545086/176233e4-9731-482f-83c8-37f8a3ff82c7">

**Comment by raynanfernandes** [comment]
https://jam.dev/c/5aa9e76e-0a3b-4e3f-9692-d1fd22b4df10
