### ISSUE TITLE
Adicionar botao de logout na pagina Dashboard

### ISSUE THREAD

**Issue by Toledodev** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-e1-proj-web-t2-daybyday#6]
O Botão deverá ficar no canto superior direito, ele deve limpar o local storage (que está com o nome de usuario atual e sua senha). O botão tambem deve redirecionar o usuario para a pagina de login

**Comment by raynanfernandes** [comment]
https://jam.dev/c/23d1fd6d-d19c-413f-a886-889c0d3a9849
